
#' Feature information
#'
#' Information about features based on three internal standards (C40H81N2O6P1,
#' C44H92N1O6P1 and C45H94N1O6P1) that have mz values between 700 and 800.
#'
#' @format data.frame as generated by the function
#' \code{\link{chem_formula_2_adducts}}
#'
#' @source Eiden et al. 2015 Genome Medicine 7:63
"info.features"

#' Feature level metabolomics data
#'
#' Metabolomics data on the feature level from two quality control samples of
#' the study MTBLS162 in the MetaboLights database reduced to mz values between
#' 700 and 800.
#'
#' @format \code{\link[SummarizedExperiment]{RangedSummarizedExperiment-class}}
#' object
#'
#' @source \url{https://www.omicsdi.org/dataset/metabolights_dataset/MTBLS162}
"se.example"

